// SPDX-License-Identifier: BSD-2-Clause

const std = @import("std");

pub const Kind = enum(u8) {
    l_paren,
    r_paren,
    l_brace,
    r_brace,
    l_bracket,
    r_bracket,
    comma,
    semicolon,
    colon,
    dot,
    dot_dot,
    dot_dot_equal,
    ellipsis,
    question,
    bang,
    tilde,
    plus,
    minus,
    star,
    slash,
    percent,
    plus_percent,
    minus_percent,
    star_percent,
    ampersand,
    pipe,
    caret,
    shl,
    shr,
    equal,
    equal_equal,
    bang_equal,
    less,
    less_equal,
    greater,
    greater_equal,
    plus_equal,
    minus_equal,
    star_equal,
    slash_equal,
    percent_equal,
    plus_percent_equal,
    minus_percent_equal,
    star_percent_equal,
    ampersand_equal,
    pipe_equal,
    caret_equal,
    shl_equal,
    shr_equal,
    fat_arrow,

    identifier,
    builtin,
    int,
    float,
    char,
    string,
    fstring,
    multiline_string,

    kw_and,
    kw_await,
    kw_break,
    kw_catch,
    kw_const,
    kw_continue,
    kw_defer,
    kw_else,
    kw_enum,
    kw_errdefer,
    kw_error,
    kw_extends,
    kw_false,
    kw_fn,
    kw_for,
    kw_if,
    kw_in,
    kw_is,
    kw_null,
    kw_or,
    kw_orelse,
    kw_return,
    kw_self,
    kw_signal,
    kw_struct,
    kw_switch,
    kw_test,
    kw_true,
    kw_try,
    kw_var,
    kw_while,

    eof,
    invalid,

    pub fn describe(kind: Kind) []const u8 {
        return switch (kind) {
            .identifier => "a name",
            .builtin => "a builtin",
            .int => "an integer",
            .float => "a float",
            .char => "a character",
            .string, .multiline_string => "a string",
            .fstring => "an f-string",
            .eof => "the end of the file",
            .invalid => "something that is not part of the language",
            else => spelling(kind).?,
        };
    }

    pub fn spelling(kind: Kind) ?[]const u8 {
        return switch (kind) {
            .l_paren => "`(`",
            .r_paren => "`)`",
            .l_brace => "`{`",
            .r_brace => "`}`",
            .l_bracket => "`[`",
            .r_bracket => "`]`",
            .comma => "`,`",
            .semicolon => "`;`",
            .colon => "`:`",
            .dot => "`.`",
            .dot_dot => "`..`",
            .dot_dot_equal => "`..=`",
            .ellipsis => "`...`",
            .question => "`?`",
            .bang => "`!`",
            .tilde => "`~`",
            .plus => "`+`",
            .minus => "`-`",
            .star => "`*`",
            .slash => "`/`",
            .percent => "`%`",
            .plus_percent => "`+%`",
            .minus_percent => "`-%`",
            .star_percent => "`*%`",
            .ampersand => "`&`",
            .pipe => "`|`",
            .caret => "`^`",
            .shl => "`<<`",
            .shr => "`>>`",
            .equal => "`=`",
            .equal_equal => "`==`",
            .bang_equal => "`!=`",
            .less => "`<`",
            .less_equal => "`<=`",
            .greater => "`>`",
            .greater_equal => "`>=`",
            .plus_equal => "`+=`",
            .minus_equal => "`-=`",
            .star_equal => "`*=`",
            .slash_equal => "`/=`",
            .percent_equal => "`%=`",
            .plus_percent_equal => "`+%=`",
            .minus_percent_equal => "`-%=`",
            .star_percent_equal => "`*%=`",
            .ampersand_equal => "`&=`",
            .pipe_equal => "`|=`",
            .caret_equal => "`^=`",
            .shl_equal => "`<<=`",
            .shr_equal => "`>>=`",
            .fat_arrow => "`=>`",
            .kw_and => "`and`",
            .kw_await => "`await`",
            .kw_break => "`break`",
            .kw_catch => "`catch`",
            .kw_const => "`const`",
            .kw_continue => "`continue`",
            .kw_defer => "`defer`",
            .kw_else => "`else`",
            .kw_enum => "`enum`",
            .kw_errdefer => "`errdefer`",
            .kw_error => "`error`",
            .kw_extends => "`extends`",
            .kw_false => "`false`",
            .kw_fn => "`fn`",
            .kw_for => "`for`",
            .kw_if => "`if`",
            .kw_in => "`in`",
            .kw_is => "`is`",
            .kw_null => "`null`",
            .kw_or => "`or`",
            .kw_orelse => "`orelse`",
            .kw_return => "`return`",
            .kw_self => "`self`",
            .kw_signal => "`signal`",
            .kw_struct => "`struct`",
            .kw_switch => "`switch`",
            .kw_test => "`test`",
            .kw_true => "`true`",
            .kw_try => "`try`",
            .kw_var => "`var`",
            .kw_while => "`while`",
            else => null,
        };
    }

    pub fn isKeyword(kind: Kind) bool {
        return @intFromEnum(kind) >= @intFromEnum(Kind.kw_and) and @intFromEnum(kind) <= @intFromEnum(Kind.kw_while);
    }
};

pub const Token = struct {
    kind: Kind,
    start: u32,
    end: u32,

    pub fn text(token: Token, source: []const u8) []const u8 {
        return source[token.start..token.end];
    }
};

pub const keywords = std.StaticStringMap(Kind).initComptime(.{
    .{ "and", .kw_and },
    .{ "await", .kw_await },
    .{ "break", .kw_break },
    .{ "catch", .kw_catch },
    .{ "const", .kw_const },
    .{ "continue", .kw_continue },
    .{ "defer", .kw_defer },
    .{ "else", .kw_else },
    .{ "enum", .kw_enum },
    .{ "errdefer", .kw_errdefer },
    .{ "error", .kw_error },
    .{ "extends", .kw_extends },
    .{ "false", .kw_false },
    .{ "fn", .kw_fn },
    .{ "for", .kw_for },
    .{ "if", .kw_if },
    .{ "in", .kw_in },
    .{ "is", .kw_is },
    .{ "null", .kw_null },
    .{ "or", .kw_or },
    .{ "orelse", .kw_orelse },
    .{ "return", .kw_return },
    .{ "self", .kw_self },
    .{ "signal", .kw_signal },
    .{ "struct", .kw_struct },
    .{ "switch", .kw_switch },
    .{ "test", .kw_test },
    .{ "true", .kw_true },
    .{ "try", .kw_try },
    .{ "var", .kw_var },
    .{ "while", .kw_while },
});
